templates:
  global:
    notify:
      task:
        title: '[TorrentBox] New Download'
        template: html
        via:
          - email:
              from: torrentbox@gmail.com
              to: reiceiver@email.com
              smtp_host: smtp.gmail.com
              smtp_port: 587
              smtp_username: torrentbox
              smtp_password: password
              smtp_tls: yes
              html: yes
    regexp:
      reject:
        - WEB
        - WEB-DL

  deluge_server:
    deluge:
      host: "localhost"
      port: 58846
      username: username_goes_here
      password: password_goes_here

  movies:
    exists_movie: /home/Videos/Movies
    seen_movies: strict
    quality: 1080p
    regexp:
      reject:
        - WEB
        - WEB-DL
        - KORSUB
        
  notification:
    email:
      active: True
      from: torrentbox@gmail.com
      to: reiceiver@email.com
      smtp_host: smtp.gmail.com
      smtp_port: 587
      smtp_username: torrentbox
      smtp_password: password
      smtp_tls: yes
      subject: '[TorrentBox] New Download'
      template: html.template        

schedules:
  # Run every task once an hour
  - tasks: '*'
    interval:
      hours: 1

tasks:

  Watchlist task:
    trakt_list:
      username: edgaras
      list: watchlist
      type: movies
    quality: 1080p 720p
    accept_all: yes
    template:
      - deluge_server
      - movies
      
  Series task:
    rss: http://www.linkomanija.net/rss.php?feed=dl&cat[]=60&cat[]=62&cat[]=46&passkey=
    series:
      - Mr Robot
      - The Big Bang Theory
      - Grand Tour
      - Game of Thrones
      - House of cards
      - Suits
      - Shameless
      - UEFA Champions League Highlights
      - Vikings
      - Westworld
      - Narcos:
          quality: 720p 1080p
    template:
      - deluge_server
    download: /home/Videos/TV_Shows
    
  Movies task:
    rss: https://www.linkomanija.net/rss.php?feed=dl&cat[]=52&passkey=
    template:
      - movies
      - deluge_server
    imdb:
      min_score: 7.5
      min_votes: 4000
      min_year: 2009
      reject_genres:
        - musical
    download: /home/Videos/Movies
