templates:
  global:
    regexp:
      reject:
        - WEB
        - WEB-DL

  deluge_server:
    deluge:
      host: "localhost"
      port: 58846
      username: username_goes_here
      password: password_goes_here

  movies:
    exists_movie: /home/Videos/
    seen_movies: strict
    quality: 1080p
    regexp:
      reject:
        - WEB
        - WEB-DL
        - KORSUB
        
  notification:
    email:
      active: True
      from: TorrentBox
      to: your@email.com
      subject: '[TorrentBox] New Download'
      template: html.template

tasks:
  Watchlist task:
    trakt_list:
      username: edgaras
      list: watchlist
      type: movies
    quality: 1080p 720p
    accept_all: yes
  Series task:
    rss: http://www.linkomanija.net/rss.php?feed=dl&cat[]=60&cat[]=62&cat[]=46&passkey=
    series:
      - Mr Robot
      - The Big Bang Theory
      - Top Gear
      - Game of Thrones
      - House of cards
      - Suits
      - UEFA Champions League Highlights
      - Vikings
      - Narcos:
          quality: 720p 1080p
    template:
      - deluge_server
      - notification
  Movies task:
    rss: https://www.linkomanija.net/rss.php?feed=dl&cat[]=52&passkey=
    template:
      - movies
      - notification
      - deluge_server
    imdb:
      min_score: 7.5
      min_votes: 4000
      min_year: 2009
      reject_genres:
        - musical
    download: /home/Videos/
